name: Website

on:
  push:
    branches: [ feat/#86-cache_for_build_artefacts_(node_modules) ]
  # allow trigger manually
  workflow_dispatch:

jobs:
  website-stage:
    name: Build and deploy stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16.5.0"
          cache: "npm"
      - name: cache gatsby cache
        uses: actions/cache@v1
        id: gatsby-cache-folder
        with:
          path: apps/website/.cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: |
            ${{ runner.os }}-cache-gatsby
      - name: cahe gatsby build
        uses: actions/cache@v1
        id: gatsby-public-folder
        with:
          path: apps/website/public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby
      - name: "install dependencies"
        run: npm install
      - name: "run tests"
        run: npx nx test website
      - name: "build website"
        run: npm run build-website
        env:
          CMS_API: ${{secrets.CMS_API_STAGE}}
      - name: deploy on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CMS_HOST_STAGE }}
          username: ${{ secrets.CMS_HOST_USERNAME_STAGE }}
          password: ${{ secrets.CMS_HOST_PASSWORD_STAGE }}
          port: ${{ secrets.CMS_HOST_PORT_STAGE }}
          source: "apps/website/public/"
          strip_components: 3
          target: ${{ secrets.CMS_HOST_TARGET_STAGE }}
