name: Deploy all affected

on:
  push:
  # allow trigger manually
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16.5.0"
          cache: "npm"
      - run: npm install
      # we squash commits before merge so we only need compare with previous HEAD
      - run: npm run affected:deploy -- --base=HEAD~1 --head=HEAD
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
